export enum AccountStatus {
    AWAITING_VERIFICATION = 'AWAITING_VERIFICATION',
    PENDING = 'PENDING',
    ACTIVE = 'ACTIVE',
    SUSPENDED = 'SUSPENDED',
    DELETED = 'DELETED',
}

export type AccountStatusType = 'AWAITING_VERIFICATION' | 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'DELETED';